const state={account:null,humanView:null,agentView:null,mode:'human'};const $=s=>document.querySelector(s);const api=async(path,options={})=>{const res=await fetch(path,{headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data};const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),3500)};
async function createAccount(event){event.preventDefault();const form=new FormData(event.target);const data=Object.fromEntries(form);try{state.account=await api('/api/onboarding/agent-account',{method:'POST',headers:{'Idempotency-Key':`web-${data.humanId}-${data.name}`},body:JSON.stringify(data)});localStorage.setItem('sinaloa-account',JSON.stringify(state.account));await loadViews();showWorkspace();toast('Workspace created — human approval is required.')}catch(error){toast(error.message)}}
async function loadViews(){const inbox=state.account.account.inbox.id;const agent=state.account.account.agent.id;state.humanView=await api(`/api/inboxes/${inbox}/human-view`);state.agentView=await api(`/api/inboxes/${inbox}/agent-view?agentId=${agent}`)}
function showWorkspace(){const agent=state.account.account.agent;$('#launch-card').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#agent-address').textContent=agent.address;$('#human-label').textContent=agent.principalHumanId;$('#workspace-label').textContent=state.account.account.inbox.name;render();if(agent.onboardingStatus==='pending_approval')$('#approval-banner').classList.remove('hidden')}
function render(){const human=state.humanView,agent=state.agentView;const view=state.mode==='human'?human:agent;const messages=state.mode==='human'?human.messages:agent.queue.assignedMessages;$('#view-eyebrow').textContent=state.mode==='human'?'HUMAN OBSERVATION LAYER':'AGENT OPERATIONS LAYER';$('#view-title').textContent=state.mode==='human'?'Activity inbox':'Execution queue';$('#message-count').textContent=human.messages.length;$('#case-count').textContent=human.cases.length;$('#asset-count').textContent=human.assets.length;$('#stat-cases').textContent=human.cases.length;$('#stat-assets').textContent=human.assets.length;const current=state.account.account.agent;$('#agent-status').textContent=current.onboardingStatus==='approved'?'Active':'Pending approval';const rows=messages.slice().reverse().map(msg=>`<article class="message"><div class="avatar">${msg.senderType==='human'?'H':'A'}</div><div><h4>${msg.senderType==='human'?'Human principal':`Agent ${escapeHtml(msg.senderAgentId||'')}`}</h4><p>${escapeHtml(msg.text)}</p><small>${new Date(msg.createdAt).toLocaleString()} · ${escapeHtml(msg.type)}</small></div><span class="tag">${escapeHtml(msg.status)}</span></article>`).join('');$('#panel').innerHTML=`<div class="panel-head"><h3>${state.mode==='human'?'All communication':'Assigned work'}</h3><span class="subtle">${messages.length} message${messages.length===1?'':'s'}</span></div>${rows||'<div class="empty"><strong>No activity yet</strong>Messages and cases will appear here in real time.</div>'}`}
async function approve(){const account=state.account.account;try{const agent=await api(`/api/inboxes/${account.inbox.id}/agent-onboarding/${account.agent.id}/approve`,{method:'POST',body:JSON.stringify({humanId:account.agent.principalHumanId,permissions:['send_agent_messages','receive_agent_messages','create_assets','execute_cases']})});state.account.account.agent=agent;localStorage.setItem('sinaloa-account',JSON.stringify(state.account));await loadViews();$('#approval-banner').classList.add('hidden');render();toast('Agent approved with execution permissions.')}catch(error){toast(error.message)}}
$('#onboarding-form').addEventListener('submit',createAccount);$('#approve').addEventListener('click',approve);document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{state.mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(item=>item.classList.toggle('active',item===button));render()}));document.querySelectorAll('[data-panel]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(item=>item.classList.toggle('active',item===button));toast(`${button.textContent.trim()} view is next in the build.`)}));$('#reset').addEventListener('click',()=>{localStorage.removeItem('sinaloa-account');location.reload()});
const saved=localStorage.getItem('sinaloa-account');if(saved){try{state.account=JSON.parse(saved);loadViews().then(showWorkspace).catch(()=>localStorage.removeItem('sinaloa-account'))}catch{localStorage.removeItem('sinaloa-account')}}
